name: Testim E2E Tests

on:
  push:
    branches:
      - main  # Runs tests on push to main

jobs:
  run-testim:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use Node.js 20 (or change to 18 if needed)

      - name: Install Testim CLI
        run: npm install -g @testim/testim-cli

      - name: Run Testim Tests
        run: |
          testim --token "${{ secrets.TESTIM_TOKEN }}" \
                 --project "6XcsY93woVA11IJ0R6Tg" \
                 --grid "Testim-Grid" \
                 --mode "selenium" \
                 --branch "Updated" \
                 --test-plan "FirstTestPlan" \
                 --timeout 60000
