name: Testim E2E Tests

on:
  push:
    branches:
      - main  # Runs tests on push to main

jobs:
  run-testim:
    runs-on: windows-latest  # ✅ Use Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # ✅ Use a specific Node.js version

      - name: Install Testim CLI
        run: npm install -g @testim/testim-cli
        shell: cmd  # ✅ Run in CMD (Command Prompt)

      - name: Run Testim Tests
        run: |
          testim --token %TESTIM_TOKEN% ^
                 --project "6XcsY93woVA11IJ0R6Tg" ^
                 --grid "Testim-Grid" ^
                 --mode "selenium" ^
                 --branch "Updated" ^
                 --test-plan "FirstTestPlan" ^
                 --timeout 60000
        shell: cmd  # ✅ Run in CMD (Command Prompt)
        env:
          TESTIM_TOKEN: ${{ secrets.TESTIM_TOKEN }}  # ✅ Use GitHub Secret
