name: Testim E2E Tests

on:
  push:
    branches:
      - main  # Run tests on push to main branch

jobs:
  run-testim:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Fetch the repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts'  # Use latest LTS version

      - name: Install Testim CLI
        run: npm install -g @testim/testim-cli  # Install Testim CLI globally

      - name: Run Testim Tests
        run: |
          testim --token "${{ secrets.TESTIM_TOKEN }}" \
                 --project "6XcsY93woVA11IJ0R6Tg" \
                 --grid "Testim-Grid" \
                 --mode "selenium" \
                 --branch "Updated" \
                 --test-plan "FirstTestPlan" \
                 --timeout 60000
